name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build --configuration=production

    - name: Debug Build Output
      shell: pwsh
      run: |
        Get-ChildItem -Path "${{ github.workspace }}/dist" -Recurse

    - name: Deploy to IIS
      shell: pwsh
      run: |
        # Define paths
        $workspace = "${{ github.workspace }}"  
        $source = Join-Path -Path $workspace -ChildPath "dist/my-angular9-app"
        $destination = "C:\inetpub\wwwroot\my-angular9-app"

        # Debugging logs
        Write-Host "Workspace: $workspace"
        Write-Host "Build Output Path: $source"

        if (-not (Test-Path -Path $source)) {
            throw "Source directory '$source' does not exist! Check your angular.json outputPath."
        }

        # Ensure destination exists and clear old files
        if (Test-Path -Path $destination) {
            Remove-Item -Path "$destination\*" -Recurse -Force
        } else {
            New-Item -ItemType Directory -Path $destination
        }

        # Set permissions
        icacls $destination /grant Everyone:(OI)(CI)F /T /Q

        # Copy new build files to IIS folder
        Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
        
        Write-Host "Files copied successfully from $source to $destination"

    - name: Restart IIS
      shell: pwsh
      run: |
        iisreset /restart
        Write-Host "IIS restarted successfully"

    - name: Print Application URL
      shell: pwsh
      run: |
        $appUrl = "http://$(hostname)/my-angular9-app"
        Write-Host "Your application is deployed and available at: $appUrl"
