name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner for better compatibility with IIS

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Node.js and build the Angular application
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --prod

    # Step 3: Deploy to IIS Server using PowerShell as adminstator
    - name: Deploy to IIS Server
      run: |
       # Define source and destination directories
       $source = "C:\Angular\dist\"
       $destination = "C:\inetpub\wwwroot\my-angular9-app"
        
        # Check if the destination folder exists; if not, create it
        if (-not (Test-Path -Path $destination)) {
            New-Item -ItemType Directory -Path $destination
        }
        
        # Copy files from source to destination
        Copy-Item -Path $source -Destination $destination -Recurse -Force
        
        Write-Host "Files copied successfully from $source to $destination"
