name: IIS server to Angular Deployment

on:
  push:
    branches:
      - dev  # Trigger deployment when changes are pushed to the 'dev' branch

jobs:
  deploy:
    runs-on: windows-latest  # Using a Windows runner for IIS deployment

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Ensure this matches your project's Node.js version

      # Step 3: Install Dependencies and Build Angular App
      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production

      # Step 4: Copy files to IIS server
      - name: Deploy to IIS server
        shell: pwsh
        run: |
          $errorActionPreference = "Stop"
          
          # Set IIS server details
          $server = "192.168.0.103"  # Replace with your IIS server's IP address
          $username = "Lavanya Gadupudi"  # Replace with your IIS server's username
          $password = "${{ secrets.IIS_PASSWORD }}"  # Store IIS password securely in GitHub secrets

          # Paths for source and destination
          $sourceDir = "${{ github.workspace }}\dist\my-angular9-app"  # Local build directory
          $destinationDir = "Z:\inetpub\wwwroot\my-angular9-app"  # Mounted drive for IIS directory
          
          # Create a credential object for authentication
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)

          # Mount a network drive for the destination folder
          New-PSDrive -Name Z -PSProvider FileSystem -Root "\\$server\wwwroot-share" -Credential $credential -Persist

          # Ensure the destination directory exists
          if (-not (Test-Path -Path $destinationDir)) {
            New-Item -ItemType Directory -Path $destinationDir
          }

          # Copy files from the Angular build directory to the IIS directory
          Copy-Item -Path "$sourceDir\*" -Destination $destinationDir -Recurse -Force
          
          # Unmount the network drive after deployment
          Remove-PSDrive -Name Z -Force
          
      # Step 5: Restart IIS (optional but recommended)
      - name: Restart IIS
        shell: pwsh
        run: |
          $errorActionPreference = "Stop"

          $server = "192.168.0.103"  # Replace with your IIS server's IP address
          $username = "Lavanya Gadupudi"  # Replace with your IIS server's username
          $password = "${{ secrets.IIS_PASSWORD }}"  # Store IIS password securely in GitHub secrets
          
          # Create a credential object
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
          
          # Restart IIS service on the server
          Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock {
            Restart-Service -Name "W3SVC"  # IIS service name
          }
