name: Deploy Angular App to AWS IIS Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to main
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js and build the Angular application
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --configuration=production

      # Step 3: Upload build files to IIS Server using SCP
      - name: Upload build files to IIS Server
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: dist/my-angular9-app
          remote: C:\inetpub\wwwroot\my-angular9-app
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          privateKey: ${{ secrets.AWS_SERVER_SSH_KEY }}  # Use SSH key instead of password
          port: 22
          verbose: true  # Enable verbose logging for debugging

      # Step 4: Restart IIS on AWS after deployment
      - name: Restart IIS on AWS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          privateKey: ${{ secrets.AWS_SERVER_SSH_KEY }}  # Use SSH key for authentication
          port: 22
          script: |
            echo "Restarting IIS..."
            sudo iisreset /restart
            echo "Angular App deployed successfully to AWS IIS!"
