name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Publish Angular Application
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build -- --prod

    # Copy Files to IIS Server's Shared Folder
    - name: Deploy to IIS Shared Folder
      run: |
        $publishPath = "C:\inetpub\wwwroot\my-angular-app"
        if (!(Test-Path -Path $publishPath)) {
          Write-Error "Publish path does not exist on the IIS server."
        }
        Copy-Item -Path .\dist\my-angular-app\* -Destination $publishPath -Recurse -Force
