name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner for better compatibility with IIS

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Node.js and build the Angular application
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --prod

    # Step 3: Deploy to IIS Server using PowerShell as adminstator
    - name: Deploy to IIS Server
      run: |
        $IIS_SERVER = "\\${{ secrets.IIS_SERVER_IP }}\wwwroot"
        $USERNAME = "${{ secrets.IIS_USER }}"
        $PASSWORD = "${{ secrets.IIS_PASSWORD }}"

        # Map network drive to IIS shared folder (using Windows)
        net use $IIS_SERVER /user:$USERNAME $PASSWORD

        # Copy the Angular build to IIS folder
        Copy-Item -Path "./dist/*" -Destination "$IIS_SERVER\my-angular-app" -Recurse -Force

        # Disconnect the mapped network drive after deployment
        net use $IIS_SERVER /delete
