name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --prod

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to IIS Server
        run: |
          ssh -o StrictHostKeyChecking=no lavig@fe80::4f8f:d8e8:a74a:d984%4 "mkdir -p C:/inetpub/wwwroot/my-angular-app"
          scp -r ./dist/* lavig@fe80::4f8f:d8e8:a74a:d984%4:C:/inetpub/wwwroot/my-angular-app/
