name: Deploy Angular to IIS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies and build Angular
    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --prod

    # Step 4: Deploy to IIS server using WinRM
    - name: Deploy to IIS server
      env:
        IIS_SERVER_IP: ${{ secrets.IIS_SERVER_IP }}
        IIS_USER: ${{ secrets.IIS_USER }}
        IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
        IIS_DEPLOY_PATH: ${{ secrets.IIS_DEPLOY_PATH }}
      run: |
        echo "Deploying to IIS server..."

        # Use PowerShell Remoting over WinRM to copy files and restart IIS
        pwsh -Command "
        $ErrorActionPreference = 'Stop'
        
        # Define credentials for IIS user
        \$securePassword = ConvertTo-SecureString '$IIS_PASSWORD' -AsPlainText -Force
        \$credential = New-Object System.Management.Automation.PSCredential ('$IIS_USER', \$securePassword)
        
        # Define IIS server and deployment path
        \$IIS_SERVER = '$IIS_SERVER_IP'
        \$DEPLOY_PATH = '$IIS_DEPLOY_PATH'
        
        # Copy files to IIS server
        Invoke-Command -ComputerName \$IIS_SERVER -Credential \$credential -ScriptBlock {
            param(\$deployPath)
            Copy-Item -Path './dist/my-angular9-app/*' -Destination \$deployPath -Recurse -Force
        } -ArgumentList \$DEPLOY_PATH

        # Restart IIS if needed
        Invoke-Command -ComputerName \$IIS_SERVER -Credential \$credential -ScriptBlock {
            iisreset
        }
        "
