name: Deploy Angular to IIS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies and build Angular project
    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --prod

    # Step 4: Deploy files using SMB
    - name: Deploy to IIS server
      env:
        IIS_SERVER_IP: ${{ secrets.IIS_SERVER_IP }}
        IIS_USER: ${{ secrets.IIS_USER }}
        IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
        IIS_DEPLOY_PATH: ${{ secrets.IIS_DEPLOY_PATH }}
      run: |
        echo "Deploying to IIS server at $IIS_SERVER_IP..."

        # Show environment variables for debugging
        echo "Deployment Path: $IIS_DEPLOY_PATH"

        # Install Samba client
        sudo apt-get update
        sudo apt-get install -y smbclient

        # List files to be deployed
        echo "Files to deploy:"
        ls dist/my-angular9-app

        # Test SMB connection (without modifying files)
        echo "$IIS_PASSWORD" | smbclient $IIS_DEPLOY_PATH -U $IIS_USER -c "ls"

        # Deploy files
        echo "$IIS_PASSWORD" | smbclient $IIS_DEPLOY_PATH -U $IIS_USER -c "
          del *;
          mput dist/my-angular9-app/*;
        "
