name: Deploy Angular App to IIS

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Downgrade to Node.js 16

    # Step 3: Install Dependencies and Build Angular App
    - name: Install Dependencies
      run: npm ci  # Clean install dependencies

    - name: Build Angular App
      run: npm run build -- --configuration=production

    # Step 4: Deploy to IIS Server
    - name: Deploy to IIS Server
      run: |
        rsync -avz -e "ssh -i ${{ secrets.IIS_SERVER_KEY }}" ./dist/my-angular9-app/ ${{ secrets.IIS_SERVER_USER }}@${{ secrets.IIS_SERVER_HOST }}:/inetpub/wwwroot/my-angular9-app/
