name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Copy Files to Deployment Directory
    - name: Copy to Deployment Directory
      run: |
        $publishPath = "C:\inetpub\wwwroot\my-angular-app"
        if (!(Test-Path -Path $publishPath)) {
          New-Item -ItemType Directory -Path $publishPath
        }
        Copy-Item -Path .\* -Destination $publishPath -Recurse -Force
