name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the 'main' branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner (or self-hosted runner with IIS installed)

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js and Install Dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    # Step 3: Build the Angular Application
    - name: Build Angular project
      run: npm run build -- --prod

    # Step 4: Deploy to IIS
    - name: Deploy to IIS
      run: |
        # Define paths
        $source = "D:\a\angularApp-deployment\angularApp-deployment\dist\my-angular9-app"  # Angular build output path
        $destination = "C:\inetpub\wwwroot\my-angular9-app"  # IIS app folder
        
        # Ensure the destination folder exists
        if (-not (Test-Path -Path $destination)) {
            New-Item -ItemType Directory -Path $destination
        }
        
        # Copy build files to IIS folder
        Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
        
        # Restart IIS to apply changes
        iisreset /restart
        
        Write-Host "Deployment complete. App is live at: http://localhost/my-angular9-app"
      shell: pwsh  # Use PowerShell Core for running the deployment script
