name: Deploy Angular App to AWS IIS Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to main
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --prod

      - name: Upload build files to IIS Server
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: dist/my-angular9-app
          remote: C:\inetpub\wwwroot\my-angular9-app
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          password: ${{ secrets.AWS_SERVER_PASS }}
          port: 22

      - name: Restart IIS on AWS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          password: ${{ secrets.AWS_SERVER_PASS }}
          port: 22
          script: |
            iisreset /restart
            echo "Angular App deployed successfully to AWS IIS!"
